### ISSUE TITLE
Command line arguments for setting the LEDManager and PortHandler

### ISSUE THREAD

**Issue by M3gaFr3ak** [Techjar/LEDCubeManager#4]
I'm working on implementing a way to enable custom communication methods for Cube-Controllers.
I thought of adding disconnect, connect, transmit methods to the LEDManager interface and creating an abstract class for the serial(COM) port so the existing ledmanagers can just extend it and stay compatible. 
Any suggestions?

**Comment by Techjar** [comment]
Doesn't the PortHandler do exactly this?

**Comment by M3gaFr3ak** [comment]
isn't the SerialPortManager pretty hardcoded to the LEDCube.java? 
Alternatively we could just add some sort of getPortHandler to the interface and default to SerialPortManager if it's null^^

Finally got the SPI bridge working w/ java btw^^

**Comment by Techjar** [comment]
It's actually completely independent of everything else, only relying on the JSSC library. And that's just the SerialPortHandler, the interface relies on nothing.

**Comment by M3gaFr3ak** [comment]
Yeah, just saw that.
But I think it might be a good idea to make the PortHandler dependent on the LEDManager, so one could just change the LEDManager and hereby change everything needed to use another cube

**Comment by Techjar** [comment]
I'm not sure that communication method and data and strictly linked together, but I suppose it's a reasonable idea. I'll add it later today, I've got some stuff to do first. Should the method return a PortHandler instance or a Class<? extends PortHandler>?

**Comment by Techjar** [comment]
There's a slight issue in that though, as then every LEDManager has to mess around with the value used for the serial port name. And the Class<> thing wouldn't work right so nevermind that.

**Comment by M3gaFr3ak** [comment]
Apart from that: I would implement commandline arguments for determining the ledmanager/portmanager (by reflection, search in the package etc.). Would you merge something like that?
Also, is the baudrate in the PortManager necessary?

**Comment by Techjar** [comment]
Yeah, I can add command line arguments for that.  Though the PortHandler will be tricky because the constructor isn't always the same.

**Comment by Techjar** [comment]
And yes, the baud rate there was a necessary implementation detail. You're free to ignore though if you so desire. I'll document that.
